### ISSUE TITLE
when i try to run the migrations i get this error

### ISSUE THREAD

**Issue by ryantupo** [PatricNox/laravel-vue-ts-docker-template#7]
![image](https://user-images.githubusercontent.com/65490793/148680280-f03156fb-6a2d-458a-8320-38031e4c0d7b.png)

**Comment by PatricNox** [comment]
Hello @ryantupo!

Is your docker running when trying this? 
Have you copied `.env.example` to `.env`? 


Also, are you using the script to run artisan? 

> ./dev.sh artisan migrate
